language: node_js
sudo: required
dist: trusty
branches:
  only:
    - master
node_js:
  - "5"
  - "6"

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - sudo apt-get install -y mongodb-org
before_script:
  - cp config-sample.js config.js